### ISSUE TITLE
Freeze Megathread

### ISSUE THREAD

**Issue by zbot473** [IceHacks/SurvivCheatInjector#105]
All comments related to freezing here; please don't create any more.

**Comment by bughitbughit** [comment]
latest patch fixed everything, what's the point of this

**Comment by IceHacks** [comment]
Some people still are experiencing issues. I haven't with this update but cannot test anymore.

**Comment by dydxcynical** [comment]
still having issues with freezing tbh

**Comment by IceHacks** [comment]
They are not major tho right? @dydxcynical

**Comment by dydxcynical** [comment]
not as before, now, I played game till end w/ no freeze

**Comment by MxrpLasHx9** [comment]
It finally fixed :D

**Comment by BaffaroDE** [comment]
Still freezing with newest patch :d

**Comment by dydxcynical** [comment]
I tried rarepotato.com proxy server and I don't freeze like in 3 games or so

**Comment by Arytor** [comment]
Yep can confirm freezing

**Comment by xKeksbyte** [comment]
Omfg Delete the old extension out of chrome, Than make new folder Extract the new into there BOOM work

**Comment by MxrpLasHx9** [comment]
Now surviv.io updated, the hack is not working again

**Comment by tokohood** [comment]
true

**Comment by HissingLambo500c** [comment]
Yep its not working anymore

**Comment by zbot473** [comment]
Fixed in latest (i think)

**Comment by DNSGriff** [comment]
Still freezes after about thirty minutes of gameplay in the new halloween mode and the old mode

**Comment by IceHacks** [comment]
Gonna patch

**Comment by Octoham** [comment]
freezes 45 sec in game

**Comment by TheSatanicAngeI** [comment]
I can't seems to find any error in console tho...

**Comment by zbot473** [comment]
There is no error, it only stops sending messages

**Comment by leoorantes08** [comment]
It has error of freezing

**Comment by zbot473** [comment]
Not in the console

**Comment by bughitbughit** [comment]
wdym console, it's a freezing error obviously

**Comment by IceHacks** [comment]
No errors

**Comment by DNSGriff** [comment]
Patched?

**Comment by IceHacks** [comment]
Still freezes but not as often in test version 1.2.1

**Comment by DNSGriff** [comment]
Where to find test version?

**Comment by DNSGriff** [comment]
Still Freezes not as much though

**Comment by ALEXXANDRO23** [comment]
You can only play half a game and it freezes :c

**Comment by DNSGriff** [comment]
Yep

**Comment by ay232** [comment]
now, it still freezes (((

**Comment by dinhanhx** [comment]
I just want to confirm that YES freezing

**Comment by Kashotex** [comment]
freeeezes

**Comment by Kashotex** [comment]
of the first circle

**Comment by IceHacks** [comment]
1.2.1 fixes freeze entirely :) Will release today :)

**Comment by Kashotex** [comment]
when?

**Comment by IceHacks** [comment]
now: https://github.com/IceHacks/SurvivCheatInjector/releases/latest

**Comment by Kashotex** [comment]
Yeah it works perfectly now, besides a few games

**Comment by Kashotex** [comment]
Played and won multiple games without freezing

**Comment by TheSatanicAngeI** [comment]
Freeze in squad...?

**Comment by IceHacks** [comment]
@TheSatanicAngeI Doesn't completely patch the freeze. You will still get it. Me and zbot are looking around.

**Comment by TheSatanicAngeI** [comment]
@zbot473 oh ok but like I dont see any changes at all 🙍 any game mode makes me freeze after 30-45 seconds.

**Comment by IceHacks** [comment]
when you press `n` it says "1.2.1" right?

**Comment by TheSatanicAngeI** [comment]
https://gyazo.com/afd3bc9c17e4d4910e4afc77585aa49c

**Comment by IceHacks** [comment]
iHASYOU lol

**Comment by TheSatanicAngeI** [comment]
Doesn't seems to freeze on duo or I got lucky and got the 1/100 games not freezing.

**Comment by PapaMoist** [comment]
IHASYOUs = shitters

**Comment by leoorantes08** [comment]
it freezed after playing 2 minutes, rip me with 15x scope

**Comment by TheSatanicAngeI** [comment]
@PapaMoist Ok retard

**Comment by DNSGriff** [comment]
IT seems like very rarely it will freeze but it does happen like 1/20 chance

**Comment by ay232** [comment]
now, it's freezes again (((((

**Comment by dinhanhx** [comment]
Rarely freeze

**Comment by SamMj2231** [comment]
Freeze almost every game, It seems the age of hacks is ending, it was our honour yo use ur hacks

**Comment by ay232** [comment]
I think, it need's to more deep upgrade. Authors of game protecting game from cheaters.

**Comment by DNSGriff** [comment]
FREEZE IS BACK

**Comment by IamRIGC** [comment]
God damn it!

**Comment by dinhanhx** [comment]
I have noticed that it MIGHT be the more players the higher chance of freezing.

**Comment by MxrpLasHx9** [comment]
Welp, maybe that is a possible reason @dinhanhx

**Comment by gohhokanntoku** [comment]
Many freezes now

**Comment by IceHacks** [comment]
Speculation is welcome, but if it has already been speculated don't speculate it again :)

**Comment by IceHacks** [comment]
[latest.zip](https://github.com/IceHacks/SurvivCheatInjector/files/3790734/latest.zip)
Have a go at this new antianticheat lol

**Comment by IceHacks** [comment]
Updated it as a release.

**Comment by lfatal1ty** [comment]
its again start freze, i download from here latest.zip and it was good about 2 hours, now again got freeze every game

**Comment by TheSatanicAngeI** [comment]
@IceHacks Still freeze 😞

**Comment by IceHacks** [comment]
I know. Gosh. No one reads :c

**Comment by HissingLambo500c** [comment]
what are the chances the anti-cheat learns how to detect cheats like the min it finds out 1 person cheats it  patches and and detects it

**Comment by leoorantes08** [comment]
it doesn't freezes, since the only error is in the backrground.js it worked good

**Comment by leoorantes08** [comment]
![Captura de Pantalla 2019-10-30 a la(s) 19 29 31](https://user-images.githubusercontent.com/57032760/67911429-221e2d00-fb4c-11e9-87e5-1bac53781e6d.png)
![Captura de Pantalla 2019-10-30 a la(s) 18 38 56](https://user-images.githubusercontent.com/57032760/67911430-221e2d00-fb4c-11e9-96f1-d6d2018b38af.png)
![Captura de Pantalla 2019-10-30 a la(s) 18 16 30](https://user-images.githubusercontent.com/57032760/67911431-221e2d00-fb4c-11e9-8275-e295c70764f4.png)
![Captura de Pantalla 2019-10-30 a la(s) 18 06 31](https://user-images.githubusercontent.com/57032760/67911432-221e2d00-fb4c-11e9-928b-2d974b54f0d9.png)

**Comment by gohhokanntoku** [comment]
New hacks don't freeze
TYGJIH

**Comment by gohhokanntoku** [comment]
Just freeze again now
hmm･･･

**Comment by leoorantes08** [comment]
Yes it started freezing

**Comment by leoorantes08** [comment]
It freezes because of the user experience
![Captura de Pantalla 2019-10-30 a la(s) 21 36 56](https://user-images.githubusercontent.com/57032760/67917067-6960e980-fb5d-11e9-8ba6-c9f505e92b73.png)

**Comment by leoorantes08** [comment]
That's the reason the game freezes

**Comment by HK1170** [comment]
> That's the reason the game freezes

do you know what to do about that ?

**Comment by leoorantes08** [comment]
no because im not the programmer, when you click on it, it says about the code of the files

**Comment by DNSGriff** [comment]
Freezing is back

**Comment by TegSpun** [comment]
After ~30 seconds, the latest version of the hack freezes. I have attached screenshots of the chrome errors. 
<img width="663" alt="Screen Shot 2019-10-31 at 8 30 59 AM" src="https://user-images.githubusercontent.com/57221456/67946959-e1103200-fbb8-11e9-9e47-060d23aa725b.png">
<img width="665" alt="Screen Shot 2019-10-31 at 8 31 05 AM" src="https://user-images.githubusercontent.com/57221456/67946960-e1103200-fbb8-11e9-96f4-0339d04289ec.png">
<img width="651" alt="Screen Shot 2019-10-31 at 8 31 10 AM" src="https://user-images.githubusercontent.com/57221456/67946961-e1103200-fbb8-11e9-971a-f3786ba5e4f7.png">

**Comment by leoorantes08** [comment]
yes that's right, the errors are freezing the game, principally the surviv.js file, i don't know what's the issue with the user experience

**Comment by DNSGriff** [comment]
Do you know if there is a way to fix it on our own or do we have to wait for devs to patch it

**Comment by TegSpun** [comment]
We're gonna have to wait for the devs.

**Comment by leoorantes08** [comment]
> Do you know if there is a way to fix it on our own or do we have to wait for devs to patch it

I don't know exactly how, since im not a dev, just im trying to find if there are some errors, i don't know exactly where the issue is

**Comment by DNSGriff** [comment]
Lol i am actually doing really well without the hacks atm.

**Comment by Space-Turtle0** [comment]
Freezing more often now.

**Comment by IceHacks** [comment]
Once again, those warnings have nothing to do with freeze :)

**Comment by leoorantes08** [comment]
> Once again, those warnings have nothing to do with freeze :)

how?

**Comment by leoorantes08** [comment]
So fix it

**Comment by IceHacks** [comment]
The errors are just warnings because I use a sync request with my code instead of the new async request which wouldn't work with my code. Has no side effects, purely cosmetic. @leoorantes08

**Comment by IceHacks** [comment]
closing this to open a new one :)
